### ISSUE TITLE
Failed import when attempting to run `python cli.py test'

### ISSUE THREAD

**Issue by GrantCuster** [victordibia/neuralqa#37]
I am attempting to follow the steps here: https://github.com/victordibia/neuralqa/blob/master/notes.md#notes-on-runningtesting-locally to run neuralqa locally. Everything seems to install fine, but when I run:
```
$ python3 neuralqa/cli.py test
```

I get the error:
```
Traceback (most recent call last):
  File "neuralqa/cli.py", line 2, in <module>
    from neuralqa.server import launch_server
ImportError: cannot import name 'launch_server'
```

**Comment by victordibia** [comment]
Thanks @GrantCuster. I updated the steps for testing locally.
